name: TypeScript Check

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20.14

            - name: Install dependencies
              run: npm ci

            - name: Type checking with TypeScript
              run: npm run typecheck
